### ISSUE TITLE
Copyright requirement prevents upstreaming ebuilds

### ISSUE THREAD

**Issue by austin987** [Obsidian-StudiosInc/os-xtoo#5]
Some of these ebuilds would be useful as dependencies of other packages I want to put in Gentoo. I'd like to avoid duplicating that effort, but the current README specifies that the Obsidian Studios copyright notice must be maintained.

Please consider removing that, or otherwise indicating that the ebuilds may be moved upstream.

**Comment by wltjr** [comment]
That is done to give credit to original author. Preserving copyright of original work is a normal part of open source. Upstream should not require that any existing copyrights be removed before inclusion.

This is a result of others within Gentoo forcing me to work on the outside for going on 8+ years. Taking my work and committing to Gentoo with just a mention in the logs is hardly credit for work done. Most tend to assume the committer did the work and do not dig into logs, etc. Like prospective employers, contractors, etc. I also do not believe taking over copyright is how normal open source projects include contributions from individual or other projects. They usually include a previous copyright line for credit purposes. I am not ok with handing over my efforts to be Copyright Gentoo only, given how I have been treated over the years. The effort is not coming from within Gentoo but from outside. That is Gentoo's own making.

The Foundation, Council, and Infrastructure, likely need to look into this matter, as there needs to be some means to share ownership/copyright. Or give credit to past authors when work is included in Gentoo. An example is the /etc/inittab file in Gentoo. Or having an Authors file as part of the meta data. Something so when ebuilds are contributed there is a better/easier trail to follow.

**Comment by austin987** [comment]
On Aug 11, 2016 7:23 AM, "William L. Thomson Jr." notifications@github.com
wrote:

> That is done to give credit to original author. Preserving copyright of
> original work is a normal part of open source. Upstream should not require
> that any existing copyrights be removed before inclusion.
> 
> This is a result of others within Gentoo forcing me to work on the
> outside for going on 8+ years. Taking my work and committing to Gentoo with
> just a mention in the logs is hardly credit for work done. Most tend to
> assume the committer did the work and do not dig into logs, etc. Like
> prospective employers, contractors, etc. I also do not believe taking over
> copyright is how normal open source projects include contributions from
> individual or other projects. They usually include a previous copyright
> line for credit purposes. I am not ok with handing over my efforts to be
> Copyright Gentoo only, given how I have been treated over the years. The
> effort is not coming from within Gentoo but from outside. That is Gentoo's
> own making.
> 
> The Foundation, Council, and Infrastructure, likely need to look into
> this matter, as there needs to be some means to share ownership/copyright.
> Or give credit to past authors when work is included in Gentoo. An example
> is the /etc/inittab file in Gentoo. Or having an Authors file as part of
> the meta data. Something so when ebuilds are contributed there is a
> better/easier trail to follow.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

Well that's not what we discussed on IRC, but it's your choice to make.

I'll duplicate efforts then.

**Comment by wltjr** [comment]
Yes it is exactly what was discussed and said in IRC. You had a meeting, and missed comments from others on the same topic.

12:16 @wizardedit wltjr, 'Most ebuilds in this overlay are Copyright Obsidian-Studios, Inc. They can be used else where, but the copyright must be respected and preserved.' I don't think I can upstream them then ;)
12:44 <+gnu_andrew> Chewi: oh seems we're the same age...
12:54 <+wltjr> wizardedit: technically all that is required is keeping a line such as that at the top. Then it can also be copyright gentoo or others just add that on top, but gentoo isn't really setup for such
12:55 @wizardedit right
12:55 <+wltjr> wizardedit: I was advised to do that by another gentoo dev, given I have been prevented from returning, so they said work in your own overlay, copyright it yourself, and let others deal
12:56 <+wltjr> wizardedit: though maybe someday people can stop preventing progress and I might be able to finally return and work in tree. I did the proxying, pr etc tried it all over the past 8 years or so...
12:56 @wizardedit wltjr, well if your company is okay with it, you can add a comment that allows transfer to Gentoo for upstreaming
12:57 <+wltjr> wizardedit: company is me so its ok, but its standard gpl stuff, anyone can take over any gpl code and make their own changes, they just have to give credit/copyright to original author and I believe release any changes
12:57 <+wltjr> mit does not require release of changes but GPL does, why prioprietary and embedded prefer, I think why PS4 is BSD vs Linux, and same with OS X, MIT vs GPL licenses
12:58 <+wltjr> otherwise they would have to give back all that stuff
12:58 <+wltjr> wizardedit: I can add something, but I do not believe its required per GPL
12:58 @wizardedit wltjr, ps4 is bsd, yes
12:58 @wizardedit wltjr, it's not GPL requirement, it's Gentoo. I just want to avoid duplicating work :)
12:59 <+wltjr> wizardedit: ps3 was linux, I think they switched for license reasons
12:59 <+wltjr> wizardedit: sure i understand, I try to avoid it as well, unless what is in tree isn't ideal and I cannot correct like osgi and some others
12:59 @wizardedit since I need newer versions of jersey anyway, but I'm sure other ebuilds you did will be useful
12:59 @wizardedit wltjr, sure
12:59 @wizardedit bbl, meeting
13:00 <+wltjr> wizardedit: I need to update it anyway, was using it sometime back but got sidetracked onto other projects, sure I need to paint :P
13:26 <+gnu_andrew> wizardedit: yes, it's Gentoo. It tries to force its own copyright in headers while having no assignment process, as far as I'm aware. It'd actually be more legally sound to leave other people's copyright in place IMHO, but IANAL.
13:36 <+wltjr> gnu_andrew: that was part of why I was advised to do as such, technically gentoo is breaching others licenses by changing that stuff, but the foundation who should oversee such I am sure is unaware
13:36 <+gnu_andrew> wltjr: yeah I had the same fight about it

It is Gentoo that is doing things incorrectly. Gentoo's policies that need to be changed. None of this is my choosing per se. I would be doing this stuff within Gentoo, and copyright would not be an issue. Gentoo has chosen to keep me on the outside for some time. As mentioned in IRC another developer suggested I create an overlay, work in that, and copyright. Knowing that Gentoo does not have policies to address such.

**Comment by austin987** [comment]
On Aug 11, 2016 8:39 AM, "William L. Thomson Jr." notifications@github.com
wrote:

> Yes it is exactly what was discussed and said in IRC. You had a meeting,
> and missed comments from others on the same topic.
> 
> 12:16 @wizardedit wltjr, 'Most ebuilds in this overlay are Copyright
> Obsidian-Studios, Inc. They can be used else where, but the copyright must
> be respected and preserved.' I don't think I can upstream them then ;)
> 12:44 <+gnu_andrew> Chewi: oh seems we're the same age...
> 12:54 <+wltjr> wizardedit: technically all that is required is keeping a
> line such as that at the top. Then it can also be copyright gentoo or
> others just add that on top, but gentoo isn't really setup for such
> 12:55 @wizardedit right
> 12:55 <+wltjr> wizardedit: I was advised to do that by another gentoo
> dev, given I have been prevented from returning, so they said work in your
> own overlay, copyright it yourself, and let others deal
> 12:56 <+wltjr> wizardedit: though maybe someday people can stop
> preventing progress and I might be able to finally return and work in tree.
> I did the proxying, pr etc tried it all over the past 8 years or so...
> 12:56 @wizardedit wltjr, well if your company is okay with it, you can
> add a comment that allows transfer to Gentoo for upstreaming
> 12:57 <+wltjr> wizardedit: company is me so its ok, but its standard gpl
> stuff, anyone can take over any gpl code and make their own changes, they
> just have to give credit/copyright to original author and I believe release
> any changes
> 12:57 <+wltjr> mit does not require release of changes but GPL does, why
> prioprietary and embedded prefer, I think why PS4 is BSD vs Linux, and same
> with OS X, MIT vs GPL licenses
> 12:58 <+wltjr> otherwise they would have to give back all that stuff
> 12:58 <+wltjr> wizardedit: I can add something, but I do not believe its
> required per GPL
> 12:58 @wizardedit wltjr, ps4 is bsd, yes
> 12:58 @wizardedit wltjr, it's not GPL requirement, it's Gentoo. I just
> want to avoid duplicating work :)
> 12:59 <+wltjr> wizardedit: ps3 was linux, I think they switched for
> license reasons
> 12:59 <+wltjr> wizardedit: sure i understand, I try to avoid it as well,
> unless what is in tree isn't ideal and I cannot correct like osgi and some
> others
> 12:59 @wizardedit since I need newer versions of jersey anyway, but I'm
> sure other ebuilds you did will be useful
> 12:59 @wizardedit wltjr, sure
> 12:59 @wizardedit bbl, meeting
> 13:00 <+wltjr> wizardedit: I need to update it anyway, was using it
> sometime back but got sidetracked onto other projects, sure I need to paint
> :P
> 13:26 <+gnu_andrew> wizardedit: yes, it's Gentoo. It tries to force its
> own copyright in headers while having no assignment process, as far as I'm
> aware. It'd actually be more legally sound to leave other people's
> copyright in place IMHO, but IANAL.
> 13:36 <+wltjr> gnu_andrew: that was part of why I was advised to do as
> such, technically gentoo is breaching others licenses by changing that
> stuff, but the foundation who should oversee such I am sure is unaware
> 13:36 <+gnu_andrew> wltjr: yeah I had the same fight about it
> 
> It is Gentoo that is doing things incorrectly. Gentoo's policies that
> need to be changed. None of this is my choosing per se. I would be doing
> this stuff within Gentoo, and copyright would not be an issue. Gentoo has
> chosen to keep me on the outside for some time. As mentioned in IRC another
> developer suggested I create an overlay, work in that, and copyright.
> Knowing that Gentoo does not have policies to address such.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

I interpreted this line differently than you, I think:
12:56 @ @wizardeditwizardedit @wizardedit wltjr, well if your company
is okay with it, you can add a comment that allows transfer to Gentoo for
upstreaming
12:57 <+wltjr> wizardedit: company is me so its ok, but its standard gpl
stuff, anyone can take over any gpl code and make their own changes, they
just have to give credit/copyright to original author and I believe release
any changes

I took "so it's OK" to mean you'd be okay with copyright assignment. I was
wrong.

I don't want to use/look at these ebuilds if you don't want them upstream,
so I'll write my own.

**Comment by wltjr** [comment]
On Thursday, August 11, 2016 09:07:28 AM Austin English wrote:

> I interpreted this line differently than you, I think:
> 12:56 @ @wizardeditwizardedit @wizardedit wltjr, well if your company
> is okay with it, you can add a comment that allows transfer to Gentoo for
> upstreaming
> 12:57 <+wltjr> wizardedit: company is me so its ok, but its standard gpl
> stuff, anyone can take over any gpl code and make their own changes, they
> just have to give credit/copyright to original author and I believe release
> any changes
> 
> I took "so it's OK" to mean you'd be okay with copyright assignment. I was
> wrong.

I meant it is ok to use, but not ok to take over copyright ownership without 
giving credit to original author. Basically once committed into Gentoo, the 
origins of said contributions are unknown. There is sometimes mention in the 
commit logs, used to exist in changelogs.

But Gentoo lacks a copyright assignment process. It seems some were looking 
into this in the past, not sure where it stands presently.

https://blog.flameeyes.eu/2012/11/a-matter-of-copyrights
https://rich0gentoo.wordpress.com/2012/12/15/gentoo-and-copyright-assignments/
https://marc.info/?t=136303687900003&r=1&w=2

I like Diego's idea of a COPYRIGHTS.gentoo or something along those lines.

> I don't want to use/look at these ebuilds if you don't want them upstream,
> so I'll write my own.

Having the ebuilds upstreamed is a sore subject. Gentoo wants if not needs my 
contributions but not me.

It was my intention to have them upstreamed, ideally with me committing them 
to tree. Given all the issues there with proxying and the PR route. Each was 
fraught with issues, delays, nitpicking, etc. It seemed others were going out 
of their way to make things more difficult to get into Gentoo. At a point I 
stopped caring if things made it into Gentoo. I am not getting any benefit from 
trying to contribute to Gentoo. It was just easier to work on my own outside 
of Gentoo.

If that work makes it back into Gentoo or not, it is up to others. I have 
already spent to much time trying to get things into Gentoo. I am not really 
keen on doing things that benefit Gentoo but do not benefit me. The work I do, I 
want credit for, and for it not to be stolen/copied into Gentoo. Given how I 
have been treated by parts of the Gentoo community.  I have no motivation to 
make things easier to get into Gentoo. My goal is otherwise, and if it ends up 
in Gentoo great.

Given Gentoo needs at least in part some of the work I have been doing. It is 
not an ideal situation. This is Gentoo's own making. Gentoo is forcing the 
policy of taking over copyrights. Not giving proper credit to contributors. 
Keeping people on the outside, but wanting or needing their work on the 
inside.

You can duplicate efforts, but you cannot duplicate direction. Any 
improvements or modifications would have to be kept in sync, or miss out. I 
made the overlay public in part to show the things Gentoo was missing out on. 
It is unfortunate you are having to waste any time here, as if it were not for 
others. This stuff would be in tree, and you could get on with other stuff.
