### ISSUE TITLE
[java 12] Osgi-foundations does not accept opendjk-bin-12

### ISSUE THREAD

**Issue by Andras-Csanyi** [Obsidian-StudiosInc/os-xtoo#52]
Hi,

I wanted to emerge maven-core and the emerge fails at osgi foundations package with the following.

The strange is that, the package says it can be built by java9+ version, and it does not accept openjdk-bin-12 as higher version.

Did I do something wrong?

```
>> Emerging (1 of 86) dev-java/osgi-foundation-1.2.0-r10::os-xtoo
 * Fetching files in the background.
 * To view fetch progress, run in another terminal:
 * tail -f /var/log/emerge-fetch.log
 * osgi-foundation-1.2.0.tar.xz BLAKE2B SHA512 size ;-) ...                                                                                                                                                                   [ ok ]
 *
 * Active Java VM (openjdk-bin-12) cannot build this package
 *
 *
 * Please use jem -S to set the correct one
 * Only Java 9+ is supported!
 *
 * ERROR: dev-java/osgi-foundation-1.2.0-r10::os-xtoo failed (setup phase):
 *   Active Java VM (openjdk-bin-12) cannot build this package
 *
 * Call stack:
 *             ebuild.sh, line  124:  Called pkg_setup
 *             ebuild.sh, line  371:  Called java-pkg_pkg_setup
 *       java-pkg.eclass, line   52:  Called java-pkg_init
 *   java-utils-2.eclass, line 1824:  Called java-pkg_switch-vm
 *   java-utils-2.eclass, line 2251:  Called java-pkg_ensure-vm-version-sufficient
 *   java-utils-2.eclass, line 1281:  Called die
 * The specific snippet of code:
 *              die "${msg}"
 *
 * If you need support, post the output of `emerge --info '=dev-java/osgi-foundation-1.2.0-r10::os-xtoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-java/osgi-foundation-1.2.0-r10::os-xtoo'`.
Please include the following information in bug reports:

JEM_VM=openjdk-bin-12
JAVA_HOME=""
COMPILER=""
JAVAC_FLAGS=""
CLASSPATH=""
emerge --info =osgi-foundation-1.2.0

localhost ~ # emerge --info =dev-java/osgi-foundation-1.2.0-r10::os-xtoo
Portage 2.3.47 (python 3.6.6-final-0, default/linux/amd64/17.0/desktop/plasma, gcc-7.3.0, glibc-2.27-r6, 4.14.63-gentoo-r1 x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-4.14.63-gentoo-r1-x86_64-Intel-R-_Core-TM-_i7-6700_CPU_@_3.40GHz-with-gentoo-2.6
KiB Mem:    32827396 total,    238280 free
KiB Swap:          0 total,         0 free
Timestamp of repository gentoo: Mon, 20 Aug 2018 14:30:01 +0000
Head commit of repository gentoo: d820ef0ab4769a6ff2a858d4c7b83ba006940ba1
Head commit of repository os-xtoo: 04c516cc5264e4b0fb6e3eae46675bb2c7aa3b2e

sh bash 4.4_p23
ld GNU ld (Gentoo 2.31.1 p1) 2.31.1
app-shells/bash:          4.4_p23::gentoo
dev-lang/perl:            5.26.2::gentoo
dev-lang/python:          2.7.15::gentoo, 3.6.6::gentoo
dev-util/cmake:           3.12.1::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.6-r1::gentoo
sys-apps/openrc:          0.38.2::gentoo
sys-apps/sandbox:         2.13::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69-r4::gentoo
sys-devel/automake:       1.16.1-r1::gentoo
sys-devel/binutils:       2.31.1::gentoo
sys-devel/gcc:            7.3.0-r3::gentoo, 8.2.0-r2::gentoo
sys-devel/gcc-config:     1.9.1::gentoo
sys-devel/libtool:        2.4.6-r5::gentoo
sys-devel/make:           4.2.1-r3::gentoo
sys-kernel/linux-headers: 4.17::gentoo (virtual/os-headers)
sys-libs/glibc:           2.27-r6::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    sync-rsync-verify-jobs: 1
    sync-rsync-extra-opts:
    sync-rsync-verify-max-age: 24
    sync-rsync-verify-metamanifest: yes

os-xtoo
    location: /usr/local/overlay/os-xtoo
    sync-type: git
    sync-uri: https://github.com/Obsidian-StudiosInc/os-xtoo.git
    masters: gentoo

dotnet
    location: /var/lib/layman/dotnet
    masters: gentoo
    priority: 50

ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=skylake -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/config /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/jem/virtuals.d /etc/jem/vms.d /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-O2 -pipe"
DISTDIR="/usr/portage/distfiles"
ENV_UNSET="DBUS_SESSION_BUS_ADDRESS DISPLAY PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync multilib-strict news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://distfiles.gentoo.org"
LANG="en_US.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j6"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X a52 aac acl acpi activities alsa amd64 berkdb bluetooth branding bzip2 cairo cdda cdr cli consolekit crypt cups cxx dbus declarative dri dts dvd dvdr emboss encode exif fam flac fortran gdbm gif glamor gpm gtk iconv ipv6 jack jpeg kde kipi kwallet lcms ldap libnotify libtirpc mad mng modules mp3 mp4 mpeg multilib ncurses nls nptl ogg opengl openmp pam pango pcre pdf phonon plasma png policykit ppds pulseaudio python qml qt5 readline samba sdl seccomp semantic-desktop spell sqlite ssl startup-notification svg tcpd tiff truetype udev udisks unicode upower usb vorbis wav widgets wxwidgets x264 xattr xcb xcomposite xml xv xvid zlib" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon plan sheets stage words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="libinput keyboard mouse" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-6 php7-0" POSTGRES_TARGETS="postgres9_5 postgres10" PYTHON_SINGLE_TARGET="python3_6" PYTHON_TARGETS="python2_7 python3_6" RUBY_TARGETS="ruby23" USERLAND="GNU" VIDEO_CARDS="nvidia" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, LINGUAS, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS
```

**Comment by wltjr** [comment]
Thanks for the report!

That is a problem in the [java-utils-2eclass](https://github.com/Obsidian-StudiosInc/os-xtoo/blob/master/eclass/java-utils-2.eclass#L1272). Something is off in the [version check function](https://github.com/Obsidian-StudiosInc/os-xtoo/blob/master/eclass/java-utils-2.eclass#L1295). Not sure why it has an issue with 12 and not 10 or 11. I have not gotten to start testing stuff with 12 yet. Just been finishing off stuff for Java 11 to be released next month. I will take a look at this ASAP. In the mean time, unless you need 12 for some reason. I would mask virtual/jdk:12, and maybe openjdk-bin:12 as well. You should not have any problems with 10 or 11.

**Comment by Andras-Csanyi** [comment]
I appreciate your work! 

I switched java11 and I get the following.

I checked, there is no openjdk file among distfiles, and I haven't found any oracle-jdk-11 on their site. Now, I'm going back to 10. It seems, it is working.

```
localhost /home/sayusi # emerge -avt jdk

 * IMPORTANT: 17 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.


These are the packages that would be merged, in reverse order:

Calculating dependencies... done!
[ebuild  NS    ] virtual/jdk-11:11::os-xtoo [1.8.0-r3:1.8::gentoo, 12:12::os-xtoo] 0 KiB
[ebuild  N     ]  dev-java/oracle-jdk-bin-11_pre25:11::os-xtoo  USE="alsa cups fontconfig -gtk2 -gtk3 -headless-awt -javafx -nsplugin (-prefix) (-selinux) -source" 176,631 KiB
[ebuild  N     ]  dev-java/openjdk-bin-11_pre25:11::os-xtoo  USE="alsa cups fontconfig -headless-awt (-prefix) (-selinux) -source" 183,203 KiB

Total: 3 packages (2 new, 1 in new slot), Size of downloads: 359,834 KiB

Would you like to merge these packages? [Yes/No]

>>> Verifying ebuild manifests

>>> Emerging (1 of 3) dev-java/openjdk-bin-11_pre25::os-xtoo
 * Fetching files in the background.
 * To view fetch progress, run in another terminal:
 * tail -f /var/log/emerge-fetch.log
>>> Downloading 'http://distfiles.gentoo.org/distfiles/openjdk-11-ea+25_linux-x64_bin.tar.gz'
--2018-08-20 23:32:33--  http://distfiles.gentoo.org/distfiles/openjdk-11-ea+25_linux-x64_bin.tar.gz
Resolving distfiles.gentoo.org... 64.50.233.100, 64.50.236.52, 137.226.34.46, ...
Connecting to distfiles.gentoo.org|64.50.233.100|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-08-20 23:32:34 ERROR 404: Not Found.

>>> Downloading 'https://download.java.net/java/early_access/jdk11/25/GPL/openjdk-11-ea+25_linux-x64_bin.tar.gz'
--2018-08-20 23:32:34--  https://download.java.net/java/early_access/jdk11/25/GPL/openjdk-11-ea+25_linux-x64_bin.tar.gz
Resolving download.java.net... 92.123.36.119
Connecting to download.java.net|92.123.36.119|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-08-20 23:32:34 ERROR 404: Not Found.

!!! Couldn't download 'openjdk-11-ea+25_linux-x64_bin.tar.gz'. Aborting.
 * Fetch failed for 'dev-java/openjdk-bin-11_pre25', Log file:
 *  '/var/tmp/portage/dev-java/openjdk-bin-11_pre25/temp/build.log'

>>> Failed to emerge dev-java/openjdk-bin-11_pre25, Log file:

>>>  '/var/tmp/portage/dev-java/openjdk-bin-11_pre25/temp/build.log'

 * Messages for package dev-java/openjdk-bin-11_pre25:

 * Fetch failed for 'dev-java/openjdk-bin-11_pre25', Log file:
 *  '/var/tmp/portage/dev-java/openjdk-bin-11_pre25/temp/build.log'
```

**Comment by wltjr** [comment]
Not sure what they are doing. Seems they dropped that version. I just noticed 26 is out, with a date of 8/9/2018. I know I have checked for a update many times since 8/9/2018. Unless they just dropped and the date is off. I just merged 12 I will push that now.

**Comment by wltjr** [comment]
I just merged oracle-jdk-bin:11 and openjdk-bin:11 pre26 and openjdk-bin:12 pre6. Though the initial problem reported for 12 remains. You should be good to go with 11. Sorry about that missing version from upstream. Not having Gentoo's package mirror system as a backup source. Though not sure if they can mirror those files or not.

**Comment by wltjr** [comment]
Here are the URLs for the various JDKs
http://jdk.java.net/10/
http://jdk.java.net/11/
http://jdk.java.net/12/

And the normal oracle one
http://www.oracle.com/technetwork/java/javase/downloads/index.html

Seems they do not keep older versions of early access or pre releases. As you discovered the hard way. I always had local copies so never noticed them being gone when I did a version bump.

Please let me know if you have other issues. I do not believe to many other than myself are using this repository at the moment. There maybe a variety of issues I have not run into yet. Also there maybe issues with the new Java system I have been working on. Which is pretty different from whats in Gentoo's main repo. Still have some things I need to package. If something you need is missing, feel free to file a issue requesting such and I will package ASAP time and package permitting. Some are a pain, and I have several I am stuck on packaging till I get more time and motivation.

Good luck, thanks for the report and checking out the repo!

**Comment by Andras-Csanyi** [comment]
I'll test them. It is a good thing you have created this repo. Gentoo as a distro is superawesome, but as java environment built from portage is rather crappy.

**Comment by wltjr** [comment]
Yes I am to aware of the Java situation on Gentoo. I was a Gentoo Java dev during its good years 06-08. Things feel apart shortly after my departure. I have tried to fix it many times since by becoming a dev again. Resulting in my being banned from all mailing list, irc, bugzilla, etc... Despite the existence of my overlay etc. Which could all be in tree if others in Gentoo did not stand in the way of progress. Which they have for a decade now. if your bored you can see some of the saga on my [dev bug](https://bugs.gentoo.org/show_bug.cgi?id=135927). I was even the most active documenter in recent years. If you view the history of the Gentoo Java docs in their wiki. I touched most of them.

It is really annoying for those who care less about Java, to stand in the way of Java moving forward on Gentoo. They have issue with me, when we would never or rarely cross paths. Given how little interest most Gentoo devs have in Java on Gentoo. Back when I was a Gentoo dev, most if not all of the Java team short of 1 or 2 people, actively coded in Java for a living. It has not been that way for a very long time. The current maintainers on occasional whim. I have no clue as to their motivation. They do not use Java much if at all. Why most packages in tree are outdated.

Some of mine are partial and work in progress. But its at least an attempt to get things current. All by 1 person. If there were more, more progress could be made. I suspect it will come to a head someday. Maybe when Java 11 is out, or 12. But long as Java 8 is supported. It will likely be moot in Gentoo. But I do not see Gentoo moving past 9. It is to much work and there are not those with the interest, time or motivation. The stuff in tree is so far behind. I have been working on this repo for 2 years or so now. With a lot more to go, but made solid progress in that time.

Still it is hard building every piece from source with no -bins. At least where I can avoid them. Building the jdk from source does not make much sense. Since you have to go back to 1.5 and bootstrap each version. Which is ridiculous to get to 12, much less 8 or 10. Thus I foresee -bins of that stuff for the foreseeable future. Not even sure whats up with icedtea in Gentoo. Nothing for 9 or 10. Which it should be called openjdk, but the maintainer is the IcedTea author, RedHat Employee, Andrew Hughes, named in icedtea in Gentoo. Which also has versions unlike any other distro.

Java on Gentoo is a big mess, and lots of legacy cruft to clean up. Its a sad situation all around. I have pretty much given up, and just seek to by pass. I use the base Gentoo, and slap my Java system on top of it. With much more work still to come in my Java efforts both in eclasses and packages. Always biting off more than I can chew, and finding some means to chew it.

**Comment by wltjr** [comment]
Found the problem it was minor, they changed the text from the javac help output from "Supported targets" to "Supported releases". In [java-utils-2.eclass](https://github.com/Obsidian-StudiosInc/os-xtoo/blob/master/eclass/java-utils-2.eclass#L1301) I grab that output and use it as an array of values for what targets/releases a given JDK supports. To ensure the JDK supports the version set by an ebuild in the RELEASE variable. Very few packages require such. With the one you ran into being one of the few, and first pulled in for install. Other packages would have built fine, as very few have the RELEASE variable set. That is needed when the package fails to build under newer targets/releases.

I guess targets was left over terminology from the era of source/target. It was natural to use it for release output. But I think they want the target concept to die, so switched it to release. Makes sense either way. I just changed to a wildcard match there. Since I need to match both releases and targets for now. But if it changes again, it should still work. Unless they change Supported to something else...

Thanks for the report! Sorry for that issue.

**Comment by Andras-Csanyi** [comment]
Thanks for fixing it.

**Comment by wltjr** [comment]
Your welcome. I am working on dev-java/maven itself, from issue #54 and #56. I packaged most the missing jars today. I will commit and push them tomorrow. Though still resolving some issues with maven cli mvn. Not sure when it will be fully usable. May have to package more stuff after I get the base maven working, the plugins/modules.
