### ISSUE TITLE
dom4j and jaxen circular dependencies

### ISSUE THREAD

**Issue by costel78** [Obsidian-StudiosInc/os-xtoo#71]
I would like to use this overlay for Netbeans. Right now, I am using openjdk from portage and netbeans-11  binary from Apache, which  is not the Gentoo way.
But I can not solve dom4j and jaxen circular dependencies.
Any advice ?

**Comment by wltjr** [comment]
Thanks for the report! I thought I had resolved that but clearly not. There are some issues opened upstream.
https://github.com/codehaus/jaxen/issues/3
https://github.com/dom4j/dom4j/issues/24

Sadly 1.6.1 also has the same issue, otherwise I would have chained them.
https://github.com/dom4j/dom4j/issues/54

Jaxen is being worked on in this repo, the codehaus one is unmaintained.
https://github.com/jaxen-xpath/jaxen/

For Jaxen 2.0 it seems they will split the stuff out. Though does not resolve the issue for jaxen 1.x and dom4j 1.x or 2.x. For now I will see about dropping support from one or the other. Seems like it will be dom4j from jaxen. I just tried to remove jaxen from dom4j, and it is used in more places beyond just the [xpath](https://github.com/dom4j/dom4j/tree/master/src/main/java/org/dom4j/xpath) folder contents.

FYI, netbeans in this overlay is still a work in progress. Some stuff is functional now, but other stuff is not. I still have a lot more pieces of netbeans to package before it is fully usable. Though, I was able to build some ant based Java projects a bit ago. Still have a lot of work for maven and gradle support, or other stuff like C/C++. I had some success with HTML, JavaScript, and CSS.

I need to move the modules into their own folders, I am dumping all jars into a single folder. Also some issue with darcula, I need to add USE flags for netbeans to make it more modular. It is a long term project that sadly I have not had much time for this year. But, I have used Netbeans for close to 2 decades, so I will continue my work to make it fully usable.

**Comment by wltjr** [comment]
I opened https://github.com/jaxen-xpath/jaxen/issues/58

This is going to be a pain to resolve! They seem pretty bound together. Dropping dom4j from jaxen...
```
 * Compiling ...
src/main/java/org/dom4j/xpath/XPathPattern.java:24: error: package org.jaxen.dom4j does not exist
import org.jaxen.dom4j.DocumentNavigator;
                      ^
src/main/java/org/dom4j/xpath/DefaultXPath.java:30: error: package org.jaxen.dom4j does not exist
import org.jaxen.dom4j.Dom4jXPath;
                      ^
src/main/java/org/dom4j/xpath/XPathPattern.java:120: error: cannot find symbol
                new SimpleVariableContext(), DocumentNavigator.getInstance());
                                             ^
  symbol:   variable DocumentNavigator
  location: class XPathPattern
src/main/java/org/dom4j/xpath/DefaultXPath.java:353: error: cannot find symbol
            return new Dom4jXPath(text);
                       ^
  symbol:   class Dom4jXPath
  location: class DefaultXPath
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors
```

Dropping jaxen from dom4j resulted in 25 errors.
I was able to drop dom4j from jaxen, but then had issues building dom4j...

Not sure what packages use dom4j from jaxen, or jaxen from dom4j. Legacy Java XML mess...

**Comment by wltjr** [comment]
@costel78 should be good to go now. The circular dep has been resolved, and I do not think I broke any dependencies in the process. Hopefully, you will not run into any more building issues. Though again keep in mind that Netbeans is still a work in progress, still being packaged and aspects are not fully functional. But, give it a go and see how far you get.

I have to make a package for ubuntu to resolve https://github.com/Obsidian-StudiosInc/ecrire/issues/45 Once that is done I can see about progressing further in Netbeans. Though, still have to get maven and gradle going, for those aspects of Netbeans.

**Comment by costel78** [comment]
I will test to compile netbeans 11 tomorrow morning. 
Thank you for your support!

**Comment by wltjr** [comment]
@costel78 it should all build and install. Though, there maybe some build issues I have not run into. Otherwise, it is the runtime you may find lacking or having issues. When you go to start netbeans, after merge.

I need to at minimum do a minimal USE flag so that only the plugin manager is available. Then you install all of the rest of NB from the plugin manager. The plugin manager works now, but some of the locally built modules conflicts with dependencies in the plugin manager. Thus, I think the fastest way to get a fully working netbeans is to install most everything via plugin manager.

Also you likely will have to manually delete ```/usr/share/netbeans-11/lib/darcula.jar``` or remove ```nb-plugins/nb-darcula``` after you merge netbeans. There are some issue there I need to look into that are mentioned upstream. I may file a bug here in this repo and mention those issues. If I do it here, it will update those issues with a link to this issue which is not relevant. Darculat is the one thing that will cause errors on start. Otherwise, it should start fine, but likely not be very usable. Till I package more stuff and get other issues resolved.

But give it a go and see what all you run into. Please feel free to open issues for anything you encounter. If its netbeans specific please add, [netbeans] to the first part of the issue for tracking. Thanks and good luck!
